// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// countOOBCohabitants
IntegerMatrix countOOBCohabitants(IntegerMatrix trainNodes, IntegerMatrix testNodes, double nTrain, double nTest);
RcppExport SEXP _forestError_countOOBCohabitants(SEXP trainNodesSEXP, SEXP testNodesSEXP, SEXP nTrainSEXP, SEXP nTestSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type trainNodes(trainNodesSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type testNodes(testNodesSEXP);
    Rcpp::traits::input_parameter< double >::type nTrain(nTrainSEXP);
    Rcpp::traits::input_parameter< double >::type nTest(nTestSEXP);
    rcpp_result_gen = Rcpp::wrap(countOOBCohabitants(trainNodes, testNodes, nTrain, nTest));
    return rcpp_result_gen;
END_RCPP
}
// countOOBCohabitantsTestPar
IntegerVector countOOBCohabitantsTestPar(IntegerMatrix trainNodes, IntegerVector testNodes, double nTrain);
RcppExport SEXP _forestError_countOOBCohabitantsTestPar(SEXP trainNodesSEXP, SEXP testNodesSEXP, SEXP nTrainSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type trainNodes(trainNodesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type testNodes(testNodesSEXP);
    Rcpp::traits::input_parameter< double >::type nTrain(nTrainSEXP);
    rcpp_result_gen = Rcpp::wrap(countOOBCohabitantsTestPar(trainNodes, testNodes, nTrain));
    return rcpp_result_gen;
END_RCPP
}
// countOOBCohabitantsTrainPar
IntegerVector countOOBCohabitantsTrainPar(IntegerVector trainNodes, IntegerMatrix testNodes, double nTest);
RcppExport SEXP _forestError_countOOBCohabitantsTrainPar(SEXP trainNodesSEXP, SEXP testNodesSEXP, SEXP nTestSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type trainNodes(trainNodesSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type testNodes(testNodesSEXP);
    Rcpp::traits::input_parameter< double >::type nTest(nTestSEXP);
    rcpp_result_gen = Rcpp::wrap(countOOBCohabitantsTrainPar(trainNodes, testNodes, nTest));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_forestError_countOOBCohabitants", (DL_FUNC) &_forestError_countOOBCohabitants, 4},
    {"_forestError_countOOBCohabitantsTestPar", (DL_FUNC) &_forestError_countOOBCohabitantsTestPar, 3},
    {"_forestError_countOOBCohabitantsTrainPar", (DL_FUNC) &_forestError_countOOBCohabitantsTrainPar, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_forestError(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
