# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

countOOBCohabitants <- function(trainNodes, testNodes, nTrain, nTest) {
    .Call('_forestError_countOOBCohabitants', PACKAGE = 'forestError', trainNodes, testNodes, nTrain, nTest)
}

countOOBCohabitantsTestPar <- function(trainNodes, testNodes, nTrain) {
    .Call('_forestError_countOOBCohabitantsTestPar', PACKAGE = 'forestError', trainNodes, testNodes, nTrain)
}

countOOBCohabitantsTrainPar <- function(trainNodes, testNodes, nTest) {
    .Call('_forestError_countOOBCohabitantsTrainPar', PACKAGE = 'forestError', trainNodes, testNodes, nTest)
}

