# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

countOOBCohabitants <- function(trainNodes, testNodes, nTrain, nTest) {
    .Call('_forestError_countOOBCohabitants', PACKAGE = 'forestError', trainNodes, testNodes, nTrain, nTest)
}

